# Generated by Django 3.2.6 on 2021-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
